### ISSUE TITLE
License problem?

### ISSUE THREAD

**Issue by aalku** [bbottema/java-socks-proxy-server#11]
Hello!

I'm interested in using your project and I dug a little into the license and I see you licensed as Apache 2.0 but your code is based on another project that is GPL v2. 

I am not expert but I don't think you can do that as GPL v2 mandates that you can only share or evolve the software mantaining the same license and Apache 2.0 is less restrictive so you are allowing others to do with the software things that the original author forbid.

**Comment by bbottema** [comment]
Hi, that's a fair question. I forked the GPL2 repo a looong time ago when I didn't know so much about it. Frankly speaking, I still find it an opaque space to communicate about.

Anyway, I went ahead and asked the original developer @damico express permission to do this. I have successfully done this for other repo's in the past so I'm optimistic. Alternatively, changing the license like this is also permissible, if the original repository has been abandoned and all original developers prove non-responsive. I don't remember where I learned about this though 🤔

**Comment by aalku** [comment]
Definitelly it doesn't work that way.  The author chooses the license and not receiving a response is not a justification to change it. I will not use "your" code. Have a good day.

**Comment by bbottema** [comment]
Wow, high horse much? There is definitely a case to be made for properly abandoned code bases where the authors can't be found anymore, but I wasn't making that case for this repo... yet. Why not wait until I get back with an answer rather than shutting the door? 

Just so you know, I obtained written permission from the original author so all is in order. I will amend the repo with this soon. Have a good day.

**Comment by bbottema** [comment]
Email from the original author [added](https://raw.githubusercontent.com/bbottema/java-socks-proxy-server/master/Source%20Code%20-%20Authorization%20of%20Use.eml) to the repo. Case closed.
